name: flutter_hooks_test

packages:
  - .

ide:
  intellij: true

scripts:
  upgrade:
    run: melos exec -- flutter pub upgrade

  get:
    run: melos exec -- flutter pub get

  analyze: melos exec -- flutter analyze .

  format: melos exec -- dart format .

  test:
    run: melos exec -- flutter test
