name: Dart CI

on:
  pull_request: {}
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Import .tool-versions
        uses: wasabeef/import-asdf-tool-versions-action@v1.1.0
        id: asdf

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.asdf.outputs.flutter }}
          cache: true

      - name: Set environment
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Get dependencies
        run: |
          dart pub global activate melos
          melos get

      - name: Run tests for our dart project.
        run: |
          melos test

      - name: Check for any formatting and statically analyze the code.
        run: |
          melos format
          melos analyze
