name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Tag pattern to match for publishing

permissions: # Job-level permissions
  contents: read # For actions/checkout
  # id-token: write # Not strictly needed when using PUB_ACCESS_TOKEN/PUB_REFRESH_TOKEN directly

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import .tool-versions
        uses: wasabeef/import-asdf-tool-versions-action@v1.1.0
        id: asdf

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.asdf.outputs.flutter }}
          cache: true

      - name: Activate Melos
        run: dart pub global activate melos

      - name: Get Melos packages
        run: melos get

      - name: Publish packages with Melos
        run: melos publish --no-dry-run --yes

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2 # Consider using a more recent version
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
