name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Tag pattern to match for publishing

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import .tool-versions
        uses: wasabeef/import-asdf-tool-versions-action@v1.1.0
        id: asdf

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.asdf.outputs.flutter }}
          cache: true

      - name: Setup Dart for publishing
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ steps.asdf.outputs.dart }}

      - name: Setup Melos
        run: dart pub global activate melos

      - name: Get Melos packages
        run: melos bootstrap

      - name: Publish package
        run: dart pub publish --force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2 # Consider using a more recent version
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
