name: Dart CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Set environment
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Get dependencies
        run: |
          dart pub global activate melos
          melos run get
      - name: Release
        uses: softprops/action-gh-release@v2
